import os
import pygame

SCREEN_ROWS = 25
SCREEN_COLS = 50
EMPTY = "EMPTY"
GARBAGE = "GARBAGE"
GARBAGE_WIDTH = 2
PLAYER_HEIGHT = 4
PLAYER_WIDTH = 2
GARBAGE_COUNT = 20
WINDOW_WIDTH = 1000
WINDOW_HEIGHT = 500
FPS = 60
